# Introduction to Neural Networks

<p style="text-justify:left; font-size:15px"> The goal is to combine theory and practice so that the people using these notebooks become familiar with the main concepts and fundamentals related to the artificial neural networks as fast as possible. In this notebook which is the first one of the series, I will cover:

<ol>
<li>What is a neuron in our body?</li>
<li>How do we mathematically model a neuron?</li>
<li>Implementing a Neuron in Pytorch</li>
<li>Implementing a Neuron in Tensorflow</li>
<li>What is an artificial neural network?</li>
<li>Implementing a feed-forward neural network in Pytorch and Tensorflow</li>
<li>How do we try to find the best weights?</li>
<li>What is Backpropagation and how is it connected to the gradient descent algorithm?</li>
<li>An example of minimizing a function using Pytorch and Gradient Descent</li>
</ol>

</p>

# 1. What is a Neuron in our body?

<center><img src="https://namra.ir/static/kaggle/neuron.png" height="300"></center>

**The structure of a neuron**

Let's envision a neuron as a tree. The roots would be the dendrites, the trunk is the cell body (also known as soma), the branches are the axon, and the leaves are the synapse.

1. **Dendrites**: These are like the roots of our neuron tree. They receive signals or messages from other neurons and pass them on towards the cell body. You can think of them as little antennas picking up signals from their surroundings.

2. **Cell Body (Soma)**: This is like the trunk of our tree. It collects and integrates information received from all the dendrites. If enough signals are received, they'll trigger an electrical impulse known as an action potential.

3. **Axon**: This is like a long branch extending out from our tree, carrying messages away from the cell body towards other neurons. The action potential travels along this 'branch', moving away from the cell body towards its end where it meets other neurons at junctions called synapses.

4. **Synapse**: These are like leaves on our neuron tree where communication with other neurons happens. When an action potential reaches these points, it triggers release of chemicals called neurotransmitters into a tiny gap between neurons called synaptic clefts. These neurotransmitters cross this gap and bind to receptors on dendrites of adjacent neurons, passing on their message.

So in summary, information flows in one direction within a neuron: from dendrites to cell body via axons, then jumps across synapses to reach next neuron's dendrites again – just like water absorbed by roots flows upwards through a tree and eventually evaporates off its leaves!

<center><img src="https://namra.ir/static/kaggle/neuron-connection.png" height="300"></center>

**What does a neuron do?**

A neuron, also known as a nerve cell, is an essential component of the nervous system. It's a fascinating little entity that has quite an important job. Its main role is to transmit information to other nerve cells, muscle, or gland cells.

Neurons are structured in a way that helps them fulfill their duties efficiently. They have a cell body which houses the nucleus, dendrites which receive signals from other neurons and axons which pass on these signals to other neurons.

When a neuron receives signals from other neurons, these signals are converted into electrical impulses. These impulses travel along the neuron's axon in one direction - towards specialized endings called synapses. At these synapses, the electrical signal gets converted into a chemical one with the help of neurotransmitters.

These neurotransmitters then cross over the synaptic gap to another neuron or target cell and bind to their receptors, thus passing on the information and keeping the communication flowing in our bodies.

Isn't it amazing how these microscopic cells play such a vital role in our daily lives? From helping us move our muscles to enabling us to think and feel - neurons truly are remarkable!

**What does it mean when we say a neuron "fires"?**

When we say a neuron "fires", it means that the neuron is transmitting information. This process, also known as an action potential, is an electrical charge that travels along the axon of a neuron. It's triggered when the cell body of the neuron receives enough signals from other neurons it's connected to. When this electrical charge reaches the end of the neuron, it triggers the release of neurotransmitters, which are chemicals that can transmit the signal to other neurons. This firing process is fundamental to all neural communication within the brain and nervous system.



Neurons can fire in response to:
- Retinal cells
- Certain edges, lines, angles, movements
- Hands and faces (in primates)
- Specific people (in humans)
- etc.

# 2. How do we mathematically model a neuron?

<center><img src="https://namra.ir/static/kaggle/neuron-mathematics.png" height="300"></center>

$x_0, x_1, x_2$: inputs to the neuron<br>
$w_0, w_1, w_2$: the neuron's weights<br>
$b$: the neuron's bias<br>
$f$: an activation function<br>
$f(\sum_i w_i x_i + b)$: the neuron's activation (output)

Note that using linear transformations, we cannot model many functions such as $y=x^2$ or the `XOR` operation. Neural networks try to solve this problem by introducing some **non-linearity**. After the linear transform is done, a non-linear function of the input will be applied to the result of the transform. This function is called the **activation function**.


An example of the activation function is sigmoid.

$$\mathrm{sigmoid}(x) = \dfrac{1}{1+e^{-x}}$$

<center><img src="https://upload.wikimedia.org/wikipedia/commons/thumb/8/88/Logistic-curve.svg/1200px-Logistic-curve.svg.png" height="400"></center>

- The sigmoid function is useful for a variety of tasks, such as classification and regression.
- The sigmoid function produces an output between 0 and 1, which makes it suitable for binary classification problems. - It can also be used to map the output of a neuron to a range between 0 and 1, which can be used to represent probabilities or confidence levels.
- Additionally, the sigmoid function has a smooth gradient, making it easier to train the network using backpropagation.
- In summary, the sigmoid function is an effective activation function for neural networks when dealing with binary classification problems or when mapping outputs to probabilities or confidence levels.



**Let's see another popular activation function**

<center><img src="https://machinelearningmastery.com/wp-content/uploads/2018/10/Line-Plot-of-Rectified-Linear-Activation-for-Negative-and-Positive-Inputs.png" height="450"></center>

- The Rectified Linear Unit (ReLU) function is a commonly used activation function in neural networks.
- It is a piece-wise linear function that returns 0 when the input is negative and returns the input when it is positive.
- This makes it useful for avoiding the vanishing gradient problem, which can occur in networks with sigmoid or tanh activation functions.
- In addition, ReLU activation functions are computationally efficient, allowing networks to train faster than with other activation functions.

- The ReLU function has become increasingly popular due to its simplicity and effectiveness.
- It can be used as an activation function in both convolutional neural networks and fully connected neural networks.
- The main advantage of using ReLU as an activation function is that it avoids the vanishing gradient problem, which can lead to slow learning in deep neural networks.
- Furthermore, ReLU has been shown to improve the accuracy of deep learning models compared to other activation functions.

In conclusion, the Rectified Linear Unit (ReLU) function is a widely used and effective activation function for neural networks due to its simplicity and ability to avoid the vanishing gradient problem. It can be used in both convolutional neural networks and fully connected neural networks, and has been shown to improve the accuracy of deep learning models compared to other activation functions.

# 3. Implementing a Neuron in Pytorch

In [ ]:
from torch import nn, sigmoid, Tensor
import numpy as np

In [ ]:
class neuron(nn.Module):

    def __init__(self, num_inputs, num_outputs):
        super(neuron, self).__init__()
        self.activation_function = sigmoid
        self.linear_transform = nn.Linear(num_inputs, num_outputs, bias=True)

    def forward(self, x):
        linear_out = self.linear_transform(x)
        out = self.activation_function(linear_out)
        return out

In [ ]:
my_neuron = neuron(num_inputs=4, num_outputs=10)

In [ ]:
my_neuron(Tensor(np.random.rand(4)))

tensor([0.4948, 0.5021, 0.4607, 0.4279, 0.3952, 0.4282, 0.4833, 0.6428, 0.5556,
        0.5303], grad_fn=<SigmoidBackward0>)

# 4. Implementing a Neuron in Tensorflow

In [ ]:
from tensorflow.keras.layers import Layer
from tensorflow import matmul

In [ ]:
class neuron(Layer):
  def __init__(self, num_inputs, num_outputs):
    super(neuron, self).__init__()
    self.num_inputs = num_inputs
    self.num_outputs = num_outputs

  def build(self, input_shape):
    self.parameters = self.add_weight("weights",
                                  shape=[self.num_inputs,
                                         self.num_outputs])

  def call(self, x):
    return matmul(x, self.parameters)

In [ ]:
my_neuron = neuron(4, 10)

In [ ]:
my_neuron(np.random.rand(1,4))

<tf.Tensor: shape=(1, 10), dtype=float32, numpy=
array([[-0.56562996,  0.4466775 ,  0.4891455 , -0.6603631 ,  0.08709814,
        -0.19837841, -0.08467681, -0.47023326,  0.7708231 , -0.20772283]],
      dtype=float32)>

# 5. What is an artificial neural network?

An artificial neural network, often simply referred to as a neural network, is a computational model inspired by the way biological brains work. It's designed to simulate the behavior of interconnected brain cells (or "neurons") in order to "learn" from large amounts of data. While a neural network does not replicate the complexity and functionality of a human brain, it can process data in a very sophisticated manner.

A neural network takes in **inputs**, which are then processed in **hidden layers** using **weights** that are adjusted during **training**. Then it delivers an **output**. This process is carried out using complex mathematical operations.

Neural networks are a key component of artificial intelligence (AI), and they're used for tasks that include automatic language translation, image recognition, and even autonomous vehicles. They have the ability to learn and improve over time when exposed to new data which makes them incredibly versatile and powerful in handling vast amounts of data and making predictions or decisions based on it.

<center><img src="https://namra.ir/static/kaggle/feed-forward-neural-network.png" height="500"></center>

In the above picture, $X = [x_1,x_2,\dots,x_n]$ is given to the network as input. We also consider a bias term for each layer which will be multiplied by 1. After $X$ is multiplied by $W$, the result will be summed with the bias and then passed to a function called the activation function. If we denote the output of the first neuron of hidden layer 1 as $h_{11}$, the weights between this neuron and $X$ as $W_{1}$, and the bias as $b_1$ we'll have:

$$h_{11} = f_1(W_1 X+b_1)$$

Similarly, for the other neurons of hidden layer 1, we'll have:

$\forall i \quad i\in\{1,2,\dots,k\}\implies \quad h_{1i} = f_i(W_i X + b_i)$

Now, consider the second hidden layer. Define $H = [h_{11}, h_{12},\dots,h_{1k}]$. The vector $H$ contains all of the outputs of hidden layer 1. Following the same notation, we'll have:

$$h_{21} = f'_2(W'_2 H+b'_2)$$

So:

$\forall i \quad i\in\{1,2,\dots,m\}\implies \quad h_{2i} = f'_i(W'_i H + b'_i)$

<br><br>

Now define $H'=[h_{21}, h_{22}, \dots, h_{2m}]$, a vector containing all of the outputs of the second hidden layer.

If we denote the outputs of the last layer by $Y=[y_1,y_2,\dots,y_o]$, we'll have:

$y_1 = f''_1(W''_1 H' + b''_1)$

So:

$\forall i \quad i\in\{1,2,\dots,o\}\implies \quad y_{i} = f''_i(W''_i H + b''_i)$

The neural network depicted above is actually called a **feed-forward neural network**. The reason is that every neuron of a layer is connected to all of the neurons of the previous and next layers.

# 6. Implementing a feed-forward neural network in Pytorch and Tensorflow

## Pytorch

The softmax function is a mathematical operation used to transform a vector of arbitrary real values into a vector of values between 0 and 1 that sum to 1. Specifically, the softmax function takes an input vector $\mathbf{x}$ with length $n$ and produces an output vector $\mathbf{y}$ with length $n$, where each element $y_i$ is calculated as:

$$y_i = \frac{\exp(x_i)}{\sum_{j=1}^n \exp(x_j)}$$

In other words, the softmax function normalizes the elements of the input vector such that their sum equals 1. This makes it useful for converting class scores into probabilities in classification tasks.

- The softmax function is a useful activation function for neural networks when the output of the network is a probability distribution.
- This is because the softmax function ensures that all of the outputs of the neural network sum to one, which is necessary for a probability distribution.
- In addition, it has been shown that using the softmax function can improve generalization performance in neural networks (See the references section).
- Therefore, it can be beneficial to use the softmax function as an activation of a neural network when the output of the network needs to represent a probability distribution.



In [ ]:
from torch import softmax

In [ ]:
class feedforward(nn.Module):
    def __init__(self):
        super(feedforward, self).__init__()
        self.hidden_layer_1 = nn.Linear(4, 10, bias=True)
        self.hidden_layer_2 = nn.Linear(10, 20, bias=True)
        self.activation_1 = sigmoid
        self.activation_2 = sigmoid
        self.output_layer = nn.Linear(20, 4, bias=True)
        self.activation_output = softmax

    def forward(self, x):
        h1_out = self.hidden_layer_1(x)
        h1_act = self.activation_1(h1_out)
        h2_out = self.hidden_layer_2(h1_act)
        h2_act = self.activation_2(h2_out)
        output = softmax(self.output_layer(h2_act), dim=0)
        return output

In [ ]:
neural_net = feedforward()

In [ ]:
neural_net(Tensor(np.random.rand(4)))

tensor([0.1363, 0.3675, 0.1623, 0.3339], grad_fn=<SoftmaxBackward0>)

## Tensorflow

In [ ]:
import numpy as np
import tensorflow as tf
import keras
from keras import layers

In [ ]:
model = keras.Sequential(
    [
        layers.Dense(10, activation="sigmoid", name="layer1"),
        layers.Dense(20, activation="sigmoid", name="layer2"),
        layers.Dense(4, activation="softmax", name="layer3"),
    ]
)

In [ ]:
x = tf.random.normal((1,4))
y = model(x)

In [ ]:
y

<tf.Tensor: shape=(1, 4), dtype=float32, numpy=array([[0.29167506, 0.24319816, 0.30839965, 0.15672715]], dtype=float32)>

# 7. How do we try to find the best weights?

<center><img src="https://namra.ir/static/kaggle/gradient-descent-explanation.png" height="500"></center>

Answer: We usually use an algorithm called "gradient descent".

Recap: The gradient of a function $f(\mathbf{x})$ is defined as the vector $\nabla f(\mathbf{x})$ whose components are the partial derivatives of $f$ with respect to each variable, i.e.

$$\nabla f(\mathbf{x}) = \left( \frac{\partial f}{\partial x_1}, \frac{\partial f}{\partial x_2}, \dots, \frac{\partial f}{\partial x_n} \right).$$

Gradient descent is an iterative optimization algorithm used to minimize a given function. It works by taking the derivatives of a given function with respect to its parameters and using them to update the parameters in the direction that minimizes the function. In mathematical notation, gradient descent can be written as:

$$\theta = \theta - \alpha \nabla_{\theta} J(\theta) $$

where $\theta$ is a vector of parameters, $\alpha$ is a learning rate, and $J(\theta)$ is the cost/loss function.


In the realm of neural networks, the loss function, also known as cost function, is a method of evaluating how well the algorithm models your given data. If predictions deviate too much from actual results, loss function would output a large number. If they're pretty accurate, it'll output a smaller number. As you change pieces of your algorithm to try and improve your model, your loss function will tell you if you're getting anywhere.

Remember, in machine learning and neural networks context, our goal is to minimize this loss function. The process of optimization involves adjusting the parameters of our model to try and reach the minimum value for our chosen loss function.

In a regression task, the loss function of a neural network can be defined as the mean squared error (MSE) between the output of the network and the desired output. Mathematically, this is expressed as:

$$L = \frac{1}{n}\sum_{i=1}^n (y_i - \hat{y_i})^2$$

where $y_i$ is the desired output for sample $i$, $\hat{y_i}$ is the predicted output for sample $i$, and $n$ is the total number of samples.


The gradient of the loss function $\nabla_{\theta} J(\theta)$ gives us the direction of steepest descent for a given set of parameters $\theta$. By taking steps in this direction, we can move closer to the global minimum of our cost/loss function. This process is repeated until we reach an acceptable level of accuracy or convergence.

# 8. What is Backpropagation and how is it connected to the gradient descent algorithm?

Backpropagation is a method used to train artificial neural networks. It is a supervised learning algorithm which uses gradient descent to optimize the weights of the network. The goal of backpropagation is to minimize the error between the predicted output and the actual output of the network.

Backpropagation works by calculating the partial derivative of the cost function with respect to each weight in the network. This tells us how much each weight contributes to the total cost of the network. We then use this information to update each weight in order to reduce the cost and improve accuracy.

Mathematically, backpropagation can be expressed as follows:
Let $C$ be a cost function, $w_i$ be a weight in our neural network, and $\sigma$ be an activation function.
The partial derivative of $C$ with respect to $w_i$ can be expressed as:
\begin{equation}
\frac{\partial C}{\partial w_i} = \sum_{j=1}^{n} \frac{\partial C}{\partial \sigma(w_j)} \frac{\partial \sigma(w_j)}{\partial w_i}
\end{equation}
where $n$ is the number of weights in our neural network.
This equation can then be used to calculate how much each weight contributes to our overall cost, allowing us to update them accordingly and improve accuracy.

# 9. An example of minimizing a function using Pytorch and Gradient Descent

$$f(x) = 3(x+2)^2$$

In [ ]:
import torch

In [ ]:
x_0 = torch.tensor(160., requires_grad=True)

In [ ]:
x = x_0

In [ ]:
optimizer = torch.optim.SGD([x], lr=0.1)
steps = 50
for i in range(steps):
    optimizer.zero_grad()
    f = 3*((x+2)**2)
    f.backward()
    optimizer.step()

In [ ]:
x

tensor(-2., requires_grad=True)